services:
  db:
    image: postgres:16
    container_name: hiring-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recruitment
    ports:
      - "5432:5432"
    volumes:
      - hiring_pgdata:/var/lib/postgresql/data

volumes:
  hiring_pgdata:
 